version: "3.9"
services:
  web:
    build: .
    ports:
      - "42069:42069"
    depends_on:
      - redis
    networks:
      - payment-net
    environment:
      - PORT=42069
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379" 
    networks:
      - payment-net

networks:
  payment-net:
    driver: bridge
